# Generated by Django 3.1.7 on 2021-04-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210428_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subimage',
            field=models.ImageField(default=' ', upload_to='blog/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(default=' ', upload_to='blog/images'),
        ),
    ]
