# Generated by Django 3.1.7 on 2021-05-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_suggestion',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('suggestion_title', models.CharField(max_length=50)),
                ('category_tag', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
