# Generated by Django 3.1.7 on 2021-05-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210511_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='code',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subimage',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='writer',
        ),
    ]
