# Generated by Django 3.1.7 on 2021-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210519_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(default='', max_length=8000),
        ),
    ]
